/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.origami.sgr.managedbeans;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;
import org.primefaces.paradise.domain.Document;
//import org.primefaces.morpheus.domain.Document;

/**
 *
 * @author Angel Navarro
 */
@Named
@ApplicationScoped
public class IconService {

    private List<Document> icons;
    private List<Document> faIcons;

    @PostConstruct
    public void createIcons() {
        icons = new ArrayList<>();
        icons.add(new Document("3d-rotation"));
        icons.add(new Document("ac-unit"));
        icons.add(new Document("access-alarm"));
        icons.add(new Document("access-alarms"));
        icons.add(new Document("access-time"));
        icons.add(new Document("accessibility"));
        icons.add(new Document("accessible"));
        icons.add(new Document("account-balance"));
        icons.add(new Document("account-balance-wallet"));
        icons.add(new Document("account-box"));
        icons.add(new Document("account-circle"));
        icons.add(new Document("adb"));
        icons.add(new Document("add"));
        icons.add(new Document("add-a-photo"));
        icons.add(new Document("add-alarm"));
        icons.add(new Document("add-alert"));
        icons.add(new Document("add-box"));
        icons.add(new Document("add-circle"));
        icons.add(new Document("add-circle-outline"));
        icons.add(new Document("add-location"));
        icons.add(new Document("add-shopping-cart"));
        icons.add(new Document("add-to-photos"));
        icons.add(new Document("add-to-queue"));
        icons.add(new Document("adjust"));
        icons.add(new Document("airline-seat-flat"));
        icons.add(new Document("airline-seat-flat-angled"));
        icons.add(new Document("airline-seat-individual-suite"));
        icons.add(new Document("airline-seat-legroom-extra"));
        icons.add(new Document("airline-seat-legroom-normal"));
        icons.add(new Document("airline-seat-legroom-reduced"));
        icons.add(new Document("airline-seat-recline-extra"));
        icons.add(new Document("airline-seat-recline-normal"));
        icons.add(new Document("airplanemode-active"));
        icons.add(new Document("airplanemode-inactive"));
        icons.add(new Document("airplay"));
        icons.add(new Document("airport-shuttle"));
        icons.add(new Document("alarm"));
        icons.add(new Document("alarm-add"));
        icons.add(new Document("alarm-off"));
        icons.add(new Document("alarm-on"));
        icons.add(new Document("album"));
        icons.add(new Document("all-inclusive"));
        icons.add(new Document("all-out"));
        icons.add(new Document("android"));
        icons.add(new Document("announcement"));
        icons.add(new Document("apps"));
        icons.add(new Document("archive"));
        icons.add(new Document("arrow-back"));
        icons.add(new Document("arrow-downward"));
        icons.add(new Document("arrow-drop-down"));
        icons.add(new Document("arrow-drop-down-circle"));
        icons.add(new Document("arrow-drop-up"));
        icons.add(new Document("arrow-forward"));
        icons.add(new Document("arrow-upward"));
        icons.add(new Document("art-track"));
        icons.add(new Document("aspect-ratio"));
        icons.add(new Document("assessment"));
        icons.add(new Document("assignment"));
        icons.add(new Document("assignment-ind"));
        icons.add(new Document("assignment-late"));
        icons.add(new Document("assignment-return"));
        icons.add(new Document("assignment-returned"));
        icons.add(new Document("assignment-turned-in"));
        icons.add(new Document("assistant"));
        icons.add(new Document("assistant-photo"));
        icons.add(new Document("attach-file"));
        icons.add(new Document("attach-money"));
        icons.add(new Document("attachment"));
        icons.add(new Document("audiotrack"));
        icons.add(new Document("autorenew"));
        icons.add(new Document("av-timer"));
        icons.add(new Document("backspace"));
        icons.add(new Document("backup"));
        icons.add(new Document("battery-alert"));
        icons.add(new Document("battery-charging-full"));
        icons.add(new Document("battery-full"));
        icons.add(new Document("battery-std"));
        icons.add(new Document("battery-unknown"));
        icons.add(new Document("beach-access"));
        icons.add(new Document("beenhere"));
        icons.add(new Document("block"));
        icons.add(new Document("bluetooth"));
        icons.add(new Document("bluetooth-audio"));
        icons.add(new Document("bluetooth-connected"));
        icons.add(new Document("bluetooth-disabled"));
        icons.add(new Document("bluetooth-searching"));
        icons.add(new Document("blur-circular"));
        icons.add(new Document("blur-linear"));
        icons.add(new Document("blur-off"));
        icons.add(new Document("blur-on"));
        icons.add(new Document("book"));
        icons.add(new Document("bookmark"));
        icons.add(new Document("bookmark-border"));
        icons.add(new Document("border-all"));
        icons.add(new Document("border-bottom"));
        icons.add(new Document("border-clear"));
        icons.add(new Document("border-color"));
        icons.add(new Document("border-horizontal"));
        icons.add(new Document("border-inner"));
        icons.add(new Document("border-left"));
        icons.add(new Document("border-outer"));
        icons.add(new Document("border-right"));
        icons.add(new Document("border-style"));
        icons.add(new Document("border-top"));
        icons.add(new Document("border-vertical"));
        icons.add(new Document("branding-watermark"));
        icons.add(new Document("brightness-1"));
        icons.add(new Document("brightness-2"));
        icons.add(new Document("brightness-3"));
        icons.add(new Document("brightness-4"));
        icons.add(new Document("brightness-5"));
        icons.add(new Document("brightness-6"));
        icons.add(new Document("brightness-7"));
        icons.add(new Document("brightness-auto"));
        icons.add(new Document("brightness-high"));
        icons.add(new Document("brightness-low"));
        icons.add(new Document("brightness-medium"));
        icons.add(new Document("broken-image"));
        icons.add(new Document("brush"));
        icons.add(new Document("bubble-chart"));
        icons.add(new Document("bug-report"));
        icons.add(new Document("build"));
        icons.add(new Document("burst-mode"));
        icons.add(new Document("business"));
        icons.add(new Document("business-center"));
        icons.add(new Document("cached"));
        icons.add(new Document("cake"));
        icons.add(new Document("call"));
        icons.add(new Document("call-end"));
        icons.add(new Document("call-made"));
        icons.add(new Document("call-merge"));
        icons.add(new Document("call-missed"));
        icons.add(new Document("call-missed-outgoing"));
        icons.add(new Document("call-received"));
        icons.add(new Document("call-split"));
        icons.add(new Document("call-to-action"));
        icons.add(new Document("camera"));
        icons.add(new Document("camera-alt"));
        icons.add(new Document("camera-enhance"));
        icons.add(new Document("camera-front"));
        icons.add(new Document("camera-rear"));
        icons.add(new Document("camera-roll"));
        icons.add(new Document("cancel"));
        icons.add(new Document("card-giftcard"));
        icons.add(new Document("card-membership"));
        icons.add(new Document("card-travel"));
        icons.add(new Document("casino"));
        icons.add(new Document("cast"));
        icons.add(new Document("cast-connected"));
        icons.add(new Document("center-focus-strong"));
        icons.add(new Document("center-focus-weak"));
        icons.add(new Document("change-history"));
        icons.add(new Document("chat"));
        icons.add(new Document("chat-bubble"));
        icons.add(new Document("chat-bubble-outline"));
        icons.add(new Document("check"));
        icons.add(new Document("check-box"));
        icons.add(new Document("check-box-outline-blank"));
        icons.add(new Document("check-circle"));
        icons.add(new Document("chevron-left"));
        icons.add(new Document("chevron-right"));
        icons.add(new Document("child-care"));
        icons.add(new Document("child-friendly"));
        icons.add(new Document("chrome-reader-mode"));
        icons.add(new Document("class"));
        icons.add(new Document("clear"));
        icons.add(new Document("clear-all"));
        icons.add(new Document("close"));
        icons.add(new Document("closed-caption"));
        icons.add(new Document("cloud"));
        icons.add(new Document("cloud-circle"));
        icons.add(new Document("cloud-done"));
        icons.add(new Document("cloud-download"));
        icons.add(new Document("cloud-off"));
        icons.add(new Document("cloud-queue"));
        icons.add(new Document("cloud-upload"));
        icons.add(new Document("code"));
        icons.add(new Document("collections"));
        icons.add(new Document("collections-bookmark"));
        icons.add(new Document("color-lens"));
        icons.add(new Document("colorize"));
        icons.add(new Document("comment"));
        icons.add(new Document("compare"));
        icons.add(new Document("compare-arrows"));
        icons.add(new Document("computer"));
        icons.add(new Document("confirmation-number"));
        icons.add(new Document("contact-mail"));
        icons.add(new Document("contact-phone"));
        icons.add(new Document("contacts"));
        icons.add(new Document("content-copy"));
        icons.add(new Document("content-cut"));
        icons.add(new Document("content-paste"));
        icons.add(new Document("control-point"));
        icons.add(new Document("control-point-duplicate"));
        icons.add(new Document("copyright"));
        icons.add(new Document("create"));
        icons.add(new Document("create-new-folder"));
        icons.add(new Document("credit-card"));
        icons.add(new Document("crop"));
        icons.add(new Document("crop-16-9"));
        icons.add(new Document("crop-3-2"));
        icons.add(new Document("crop-5-4"));
        icons.add(new Document("crop-7-5"));
        icons.add(new Document("crop-din"));
        icons.add(new Document("crop-free"));
        icons.add(new Document("crop-landscape"));
        icons.add(new Document("crop-original"));
        icons.add(new Document("crop-portrait"));
        icons.add(new Document("crop-rotate"));
        icons.add(new Document("crop-square"));
        icons.add(new Document("dashboard"));
        icons.add(new Document("data-usage"));
        icons.add(new Document("date-range"));
        icons.add(new Document("dehaze"));
        icons.add(new Document("delete"));
        icons.add(new Document("delete-forever"));
        icons.add(new Document("delete-sweep"));
        icons.add(new Document("description"));
        icons.add(new Document("desktop-mac"));
        icons.add(new Document("desktop-windows"));
        icons.add(new Document("details"));
        icons.add(new Document("developer-board"));
        icons.add(new Document("developer-mode"));
        icons.add(new Document("device-hub"));
        icons.add(new Document("devices"));
        icons.add(new Document("devices-other"));
        icons.add(new Document("dialer-sip"));
        icons.add(new Document("dialpad"));
        icons.add(new Document("directions"));
        icons.add(new Document("directions-bike"));
        icons.add(new Document("directions-boat"));
        icons.add(new Document("directions-bus"));
        icons.add(new Document("directions-car"));
        icons.add(new Document("directions-railway"));
        icons.add(new Document("directions-run"));
        icons.add(new Document("directions-subway"));
        icons.add(new Document("directions-transit"));
        icons.add(new Document("directions-walk"));
        icons.add(new Document("disc-full"));
        icons.add(new Document("dns"));
        icons.add(new Document("do-not-disturb"));
        icons.add(new Document("do-not-disturb-alt"));
        icons.add(new Document("do-not-disturb-off"));
        icons.add(new Document("do-not-disturb-on"));
        icons.add(new Document("dock"));
        icons.add(new Document("domain"));
        icons.add(new Document("done"));
        icons.add(new Document("done-all"));
        icons.add(new Document("donut-large"));
        icons.add(new Document("donut-small"));
        icons.add(new Document("drafts"));
        icons.add(new Document("drag-handle"));
        icons.add(new Document("drive-eta"));
        icons.add(new Document("dvr"));
        icons.add(new Document("edit"));
        icons.add(new Document("edit-location"));
        icons.add(new Document("eject"));
        icons.add(new Document("email"));
        icons.add(new Document("enhanced-encryption"));
        icons.add(new Document("equalizer"));
        icons.add(new Document("error"));
        icons.add(new Document("error-outline"));
        icons.add(new Document("euro-symbol"));
        icons.add(new Document("ev-station"));
        icons.add(new Document("event"));
        icons.add(new Document("event-available"));
        icons.add(new Document("event-busy"));
        icons.add(new Document("event-note"));
        icons.add(new Document("event-seat"));
        icons.add(new Document("exit-to-app"));
        icons.add(new Document("expand-less"));
        icons.add(new Document("expand-more"));
        icons.add(new Document("explicit"));
        icons.add(new Document("explore"));
        icons.add(new Document("exposure"));
        icons.add(new Document("exposure-neg-1"));
        icons.add(new Document("exposure-neg-2"));
        icons.add(new Document("exposure-plus-1"));
        icons.add(new Document("exposure-plus-2"));
        icons.add(new Document("exposure-zero"));
        icons.add(new Document("extension"));
        icons.add(new Document("face"));
        icons.add(new Document("fast-forward"));
        icons.add(new Document("fast-rewind"));
        icons.add(new Document("favorite"));
        icons.add(new Document("favorite-border"));
        icons.add(new Document("featured-play-list"));
        icons.add(new Document("featured-video"));
        icons.add(new Document("feedback"));
        icons.add(new Document("fiber-dvr"));
        icons.add(new Document("fiber-manual-record"));
        icons.add(new Document("fiber-new"));
        icons.add(new Document("fiber-pin"));
        icons.add(new Document("fiber-smart-record"));
        icons.add(new Document("file-download"));
        icons.add(new Document("file-upload"));
        icons.add(new Document("filter"));
        icons.add(new Document("filter-1"));
        icons.add(new Document("filter-2"));
        icons.add(new Document("filter-3"));
        icons.add(new Document("filter-4"));
        icons.add(new Document("filter-5"));
        icons.add(new Document("filter-6"));
        icons.add(new Document("filter-7"));
        icons.add(new Document("filter-8"));
        icons.add(new Document("filter-9"));
        icons.add(new Document("filter-9-plus"));
        icons.add(new Document("filter-b-and-w"));
        icons.add(new Document("filter-center-focus"));
        icons.add(new Document("filter-drama"));
        icons.add(new Document("filter-frames"));
        icons.add(new Document("filter-hdr"));
        icons.add(new Document("filter-list"));
        icons.add(new Document("filter-none"));
        icons.add(new Document("filter-tilt-shift"));
        icons.add(new Document("filter-vintage"));
        icons.add(new Document("find-in-page"));
        icons.add(new Document("find-replace"));
        icons.add(new Document("fingerprint"));
        icons.add(new Document("first-page"));
        icons.add(new Document("fitness-center"));
        icons.add(new Document("flag"));
        icons.add(new Document("flare"));
        icons.add(new Document("flash-auto"));
        icons.add(new Document("flash-off"));
        icons.add(new Document("flash-on"));
        icons.add(new Document("flight"));
        icons.add(new Document("flight-land"));
        icons.add(new Document("flight-takeoff"));
        icons.add(new Document("flip"));
        icons.add(new Document("flip-to-back"));
        icons.add(new Document("flip-to-front"));
        icons.add(new Document("folder"));
        icons.add(new Document("folder-open"));
        icons.add(new Document("folder-shared"));
        icons.add(new Document("folder-special"));
        icons.add(new Document("font-download"));
        icons.add(new Document("format-align-center"));
        icons.add(new Document("format-align-justify"));
        icons.add(new Document("format-align-left"));
        icons.add(new Document("format-align-right"));
        icons.add(new Document("format-bold"));
        icons.add(new Document("format-clear"));
        icons.add(new Document("format-color-fill"));
        icons.add(new Document("format-color-reset"));
        icons.add(new Document("format-color-text"));
        icons.add(new Document("format-indent-decrease"));
        icons.add(new Document("format-indent-increase"));
        icons.add(new Document("format-italic"));
        icons.add(new Document("format-line-spacing"));
        icons.add(new Document("format-list-bulleted"));
        icons.add(new Document("format-list-numbered"));
        icons.add(new Document("format-paint"));
        icons.add(new Document("format-quote"));
        icons.add(new Document("format-shapes"));
        icons.add(new Document("format-size"));
        icons.add(new Document("format-strikethrough"));
        icons.add(new Document("format-textdirection-l-to-r"));
        icons.add(new Document("format-textdirection-r-to-l"));
        icons.add(new Document("format-underlined"));
        icons.add(new Document("forum"));
        icons.add(new Document("forward"));
        icons.add(new Document("forward-10"));
        icons.add(new Document("forward-30"));
        icons.add(new Document("forward-5"));
        icons.add(new Document("free-breakfast"));
        icons.add(new Document("fullscreen"));
        icons.add(new Document("fullscreen-exit"));
        icons.add(new Document("functions"));
        icons.add(new Document("g-translate"));
        icons.add(new Document("gamepad"));
        icons.add(new Document("games"));
        icons.add(new Document("gavel"));
        icons.add(new Document("gesture"));
        icons.add(new Document("get-app"));
        icons.add(new Document("gif"));
        icons.add(new Document("golf-course"));
        icons.add(new Document("gps-fixed"));
        icons.add(new Document("gps-not-fixed"));
        icons.add(new Document("gps-off"));
        icons.add(new Document("grade"));
        icons.add(new Document("gradient"));
        icons.add(new Document("grain"));
        icons.add(new Document("graphic-eq"));
        icons.add(new Document("grid-off"));
        icons.add(new Document("grid-on"));
        icons.add(new Document("group"));
        icons.add(new Document("group-add"));
        icons.add(new Document("group-work"));
        icons.add(new Document("hd"));
        icons.add(new Document("hdr-off"));
        icons.add(new Document("hdr-on"));
        icons.add(new Document("hdr-strong"));
        icons.add(new Document("hdr-weak"));
        icons.add(new Document("headset"));
        icons.add(new Document("headset-mic"));
        icons.add(new Document("healing"));
        icons.add(new Document("hearing"));
        icons.add(new Document("help"));
        icons.add(new Document("help-outline"));
        icons.add(new Document("high-quality"));
        icons.add(new Document("highlight"));
        icons.add(new Document("highlight-off"));
        icons.add(new Document("history"));
        icons.add(new Document("home"));
        icons.add(new Document("hot-tub"));
        icons.add(new Document("hotel"));
        icons.add(new Document("hourglass-empty"));
        icons.add(new Document("hourglass-full"));
        icons.add(new Document("http"));
        icons.add(new Document("https"));
        icons.add(new Document("image"));
        icons.add(new Document("image-aspect-ratio"));
        icons.add(new Document("import-contacts"));
        icons.add(new Document("import-export"));
        icons.add(new Document("important-devices"));
        icons.add(new Document("inbox"));
        icons.add(new Document("indeterminate-check-box"));
        icons.add(new Document("info"));
        icons.add(new Document("info-outline"));
        icons.add(new Document("input"));
        icons.add(new Document("insert-chart"));
        icons.add(new Document("insert-comment"));
        icons.add(new Document("insert-drive-file"));
        icons.add(new Document("insert-emoticon"));
        icons.add(new Document("insert-invitation"));
        icons.add(new Document("insert-link"));
        icons.add(new Document("insert-photo"));
        icons.add(new Document("invert-colors"));
        icons.add(new Document("invert-colors-off"));
        icons.add(new Document("iso"));
        icons.add(new Document("keyboard"));
        icons.add(new Document("keyboard-arrow-down"));
        icons.add(new Document("keyboard-arrow-left"));
        icons.add(new Document("keyboard-arrow-right"));
        icons.add(new Document("keyboard-arrow-up"));
        icons.add(new Document("keyboard-backspace"));
        icons.add(new Document("keyboard-capslock"));
        icons.add(new Document("keyboard-hide"));
        icons.add(new Document("keyboard-return"));
        icons.add(new Document("keyboard-tab"));
        icons.add(new Document("keyboard-voice"));
        icons.add(new Document("kitchen"));
        icons.add(new Document("label"));
        icons.add(new Document("label-outline"));
        icons.add(new Document("landscape"));
        icons.add(new Document("language"));
        icons.add(new Document("laptop"));
        icons.add(new Document("laptop-chromebook"));
        icons.add(new Document("laptop-mac"));
        icons.add(new Document("laptop-windows"));
        icons.add(new Document("last-page"));
        icons.add(new Document("launch"));
        icons.add(new Document("layers"));
        icons.add(new Document("layers-clear"));
        icons.add(new Document("leak-add"));
        icons.add(new Document("leak-remove"));
        icons.add(new Document("lens"));
        icons.add(new Document("library-add"));
        icons.add(new Document("library-books"));
        icons.add(new Document("library-music"));
        icons.add(new Document("lightbulb-outline"));
        icons.add(new Document("line-style"));
        icons.add(new Document("line-weight"));
        icons.add(new Document("linear-scale"));
        icons.add(new Document("link"));
        icons.add(new Document("linked-camera"));
        icons.add(new Document("list"));
        icons.add(new Document("live-help"));
        icons.add(new Document("live-tv"));
        icons.add(new Document("local-activity"));
        icons.add(new Document("local-airport"));
        icons.add(new Document("local-atm"));
        icons.add(new Document("local-bar"));
        icons.add(new Document("local-cafe"));
        icons.add(new Document("local-car-wash"));
        icons.add(new Document("local-convenience-store"));
        icons.add(new Document("local-dining"));
        icons.add(new Document("local-drink"));
        icons.add(new Document("local-florist"));
        icons.add(new Document("local-gas-station"));
        icons.add(new Document("local-grocery-store"));
        icons.add(new Document("local-hospital"));
        icons.add(new Document("local-hotel"));
        icons.add(new Document("local-laundry-service"));
        icons.add(new Document("local-library"));
        icons.add(new Document("local-mall"));
        icons.add(new Document("local-movies"));
        icons.add(new Document("local-offer"));
        icons.add(new Document("local-parking"));
        icons.add(new Document("local-pharmacy"));
        icons.add(new Document("local-phone"));
        icons.add(new Document("local-pizza"));
        icons.add(new Document("local-play"));
        icons.add(new Document("local-post-office"));
        icons.add(new Document("local-printshop"));
        icons.add(new Document("local-see"));
        icons.add(new Document("local-shipping"));
        icons.add(new Document("local-taxi"));
        icons.add(new Document("location-city"));
        icons.add(new Document("location-disabled"));
        icons.add(new Document("location-off"));
        icons.add(new Document("location-on"));
        icons.add(new Document("location-searching"));
        icons.add(new Document("lock"));
        icons.add(new Document("lock-open"));
        icons.add(new Document("lock-outline"));
        icons.add(new Document("looks"));
        icons.add(new Document("looks-3"));
        icons.add(new Document("looks-4"));
        icons.add(new Document("looks-5"));
        icons.add(new Document("looks-6"));
        icons.add(new Document("looks-one"));
        icons.add(new Document("looks-two"));
        icons.add(new Document("loop"));
        icons.add(new Document("loupe"));
        icons.add(new Document("low-priority"));
        icons.add(new Document("loyalty"));
        icons.add(new Document("mail"));
        icons.add(new Document("mail-outline"));
        icons.add(new Document("map"));
        icons.add(new Document("markunread"));
        icons.add(new Document("markunread-mailbox"));
        icons.add(new Document("memory"));
        icons.add(new Document("menu"));
        icons.add(new Document("merge-type"));
        icons.add(new Document("message"));
        icons.add(new Document("mic"));
        icons.add(new Document("mic-none"));
        icons.add(new Document("mic-off"));
        icons.add(new Document("mms"));
        icons.add(new Document("mode-comment"));
        icons.add(new Document("mode-edit"));
        icons.add(new Document("monetization-on"));
        icons.add(new Document("money-off"));
        icons.add(new Document("monochrome-photos"));
        icons.add(new Document("mood"));
        icons.add(new Document("mood-bad"));
        icons.add(new Document("more"));
        icons.add(new Document("more-horiz"));
        icons.add(new Document("more-vert"));
        icons.add(new Document("motorcycle"));
        icons.add(new Document("mouse"));
        icons.add(new Document("move-to-inbox"));
        icons.add(new Document("movie"));
        icons.add(new Document("movie-creation"));
        icons.add(new Document("movie-filter"));
        icons.add(new Document("multiline-chart"));
        icons.add(new Document("music-note"));
        icons.add(new Document("music-video"));
        icons.add(new Document("my-location"));
        icons.add(new Document("nature"));
        icons.add(new Document("nature-people"));
        icons.add(new Document("navigate-before"));
        icons.add(new Document("navigate-next"));
        icons.add(new Document("navigation"));
        icons.add(new Document("near-me"));
        icons.add(new Document("network-cell"));
        icons.add(new Document("network-check"));
        icons.add(new Document("network-locked"));
        icons.add(new Document("network-wifi"));
        icons.add(new Document("new-releases"));
        icons.add(new Document("next-week"));
        icons.add(new Document("nfc"));
        icons.add(new Document("no-encryption"));
        icons.add(new Document("no-sim"));
        icons.add(new Document("not-interested"));
        icons.add(new Document("note"));
        icons.add(new Document("note-add"));
        icons.add(new Document("notifications"));
        icons.add(new Document("notifications-active"));
        icons.add(new Document("notifications-none"));
        icons.add(new Document("notifications-off"));
        icons.add(new Document("notifications-paused"));
        icons.add(new Document("offline-pin"));
        icons.add(new Document("ondemand-video"));
        icons.add(new Document("opacity"));
        icons.add(new Document("open-in-browser"));
        icons.add(new Document("open-in-new"));
        icons.add(new Document("open-with"));
        icons.add(new Document("pages"));
        icons.add(new Document("pageview"));
        icons.add(new Document("palette"));
        icons.add(new Document("pan-tool"));
        icons.add(new Document("panorama"));
        icons.add(new Document("panorama-fish-eye"));
        icons.add(new Document("panorama-horizontal"));
        icons.add(new Document("panorama-vertical"));
        icons.add(new Document("panorama-wide-angle"));
        icons.add(new Document("party-mode"));
        icons.add(new Document("pause"));
        icons.add(new Document("pause-circle-filled"));
        icons.add(new Document("pause-circle-outline"));
        icons.add(new Document("payment"));
        icons.add(new Document("people"));
        icons.add(new Document("people-outline"));
        icons.add(new Document("perm-camera-mic"));
        icons.add(new Document("perm-contact-calendar"));
        icons.add(new Document("perm-data-setting"));
        icons.add(new Document("perm-device-information"));
        icons.add(new Document("perm-identity"));
        icons.add(new Document("perm-media"));
        icons.add(new Document("perm-phone-msg"));
        icons.add(new Document("perm-scan-wifi"));
        icons.add(new Document("person"));
        icons.add(new Document("person-add"));
        icons.add(new Document("person-outline"));
        icons.add(new Document("person-pin"));
        icons.add(new Document("person-pin-circle"));
        icons.add(new Document("personal-video"));
        icons.add(new Document("pets"));
        icons.add(new Document("phone"));
        icons.add(new Document("phone-android"));
        icons.add(new Document("phone-bluetooth-speaker"));
        icons.add(new Document("phone-forwarded"));
        icons.add(new Document("phone-in-talk"));
        icons.add(new Document("phone-iphone"));
        icons.add(new Document("phone-locked"));
        icons.add(new Document("phone-missed"));
        icons.add(new Document("phone-paused"));
        icons.add(new Document("phonelink"));
        icons.add(new Document("phonelink-erase"));
        icons.add(new Document("phonelink-lock"));
        icons.add(new Document("phonelink-off"));
        icons.add(new Document("phonelink-ring"));
        icons.add(new Document("phonelink-setup"));
        icons.add(new Document("photo"));
        icons.add(new Document("photo-album"));
        icons.add(new Document("photo-camera"));
        icons.add(new Document("photo-filter"));
        icons.add(new Document("photo-library"));
        icons.add(new Document("photo-size-select-actual"));
        icons.add(new Document("photo-size-select-large"));
        icons.add(new Document("photo-size-select-small"));
        icons.add(new Document("picture-as-pdf"));
        icons.add(new Document("picture-in-picture"));
        icons.add(new Document("picture-in-picture-alt"));
        icons.add(new Document("pie-chart"));
        icons.add(new Document("pie-chart-outlined"));
        icons.add(new Document("pin-drop"));
        icons.add(new Document("place"));
        icons.add(new Document("play-arrow"));
        icons.add(new Document("play-circle-filled"));
        icons.add(new Document("play-circle-outline"));
        icons.add(new Document("play-for-work"));
        icons.add(new Document("playlist-add"));
        icons.add(new Document("playlist-add-check"));
        icons.add(new Document("playlist-play"));
        icons.add(new Document("plus-one"));
        icons.add(new Document("poll"));
        icons.add(new Document("polymer"));
        icons.add(new Document("pool"));
        icons.add(new Document("portable-wifi-off"));
        icons.add(new Document("portrait"));
        icons.add(new Document("power"));
        icons.add(new Document("power-input"));
        icons.add(new Document("power-settings-new"));
        icons.add(new Document("pregnant-woman"));
        icons.add(new Document("present-to-all"));
        icons.add(new Document("print"));
        icons.add(new Document("priority-high"));
        icons.add(new Document("public"));
        icons.add(new Document("publish"));
        icons.add(new Document("query-builder"));
        icons.add(new Document("question-answer"));
        icons.add(new Document("queue"));
        icons.add(new Document("queue-music"));
        icons.add(new Document("queue-play-next"));
        icons.add(new Document("radio"));
        icons.add(new Document("radio-button-checked"));
        icons.add(new Document("radio-button-unchecked"));
        icons.add(new Document("rate-review"));
        icons.add(new Document("receipt"));
        icons.add(new Document("recent-actors"));
        icons.add(new Document("record-voice-over"));
        icons.add(new Document("redeem"));
        icons.add(new Document("redo"));
        icons.add(new Document("refresh"));
        icons.add(new Document("remove"));
        icons.add(new Document("remove-circle"));
        icons.add(new Document("remove-circle-outline"));
        icons.add(new Document("remove-from-queue"));
        icons.add(new Document("remove-red-eye"));
        icons.add(new Document("remove-shopping-cart"));
        icons.add(new Document("reorder"));
        icons.add(new Document("repeat"));
        icons.add(new Document("repeat-one"));
        icons.add(new Document("replay"));
        icons.add(new Document("replay-10"));
        icons.add(new Document("replay-30"));
        icons.add(new Document("replay-5"));
        icons.add(new Document("reply"));
        icons.add(new Document("reply-all"));
        icons.add(new Document("report"));
        icons.add(new Document("report-problem"));
        icons.add(new Document("restaurant"));
        icons.add(new Document("restaurant-menu"));
        icons.add(new Document("restore"));
        icons.add(new Document("restore-page"));
        icons.add(new Document("ring-volume"));
        icons.add(new Document("room"));
        icons.add(new Document("room-service"));
        icons.add(new Document("rotate-90-degrees-ccw"));
        icons.add(new Document("rotate-left"));
        icons.add(new Document("rotate-right"));
        icons.add(new Document("rounded-corner"));
        icons.add(new Document("router"));
        icons.add(new Document("rowing"));
        icons.add(new Document("rss-feed"));
        icons.add(new Document("rv-hookup"));
        icons.add(new Document("satellite"));
        icons.add(new Document("save"));
        icons.add(new Document("scanner"));
        icons.add(new Document("schedule"));
        icons.add(new Document("school"));
        icons.add(new Document("screen-lock-landscape"));
        icons.add(new Document("screen-lock-portrait"));
        icons.add(new Document("screen-lock-rotation"));
        icons.add(new Document("screen-rotation"));
        icons.add(new Document("screen-share"));
        icons.add(new Document("sd-card"));
        icons.add(new Document("sd-storage"));
        icons.add(new Document("search"));
        icons.add(new Document("security"));
        icons.add(new Document("select-all"));
        icons.add(new Document("send"));
        icons.add(new Document("sentiment-dissatisfied"));
        icons.add(new Document("sentiment-neutral"));
        icons.add(new Document("sentiment-satisfied"));
        icons.add(new Document("sentiment-very-dissatisfied"));
        icons.add(new Document("sentiment-very-satisfied"));
        icons.add(new Document("settings"));
        icons.add(new Document("settings-applications"));
        icons.add(new Document("settings-backup-restore"));
        icons.add(new Document("settings-bluetooth"));
        icons.add(new Document("settings-brightness"));
        icons.add(new Document("settings-cell"));
        icons.add(new Document("settings-ethernet"));
        icons.add(new Document("settings-input-antenna"));
        icons.add(new Document("settings-input-component"));
        icons.add(new Document("settings-input-composite"));
        icons.add(new Document("settings-input-hdmi"));
        icons.add(new Document("settings-input-svideo"));
        icons.add(new Document("settings-overscan"));
        icons.add(new Document("settings-phone"));
        icons.add(new Document("settings-power"));
        icons.add(new Document("settings-remote"));
        icons.add(new Document("settings-system-daydream"));
        icons.add(new Document("settings-voice"));
        icons.add(new Document("share"));
        icons.add(new Document("shop"));
        icons.add(new Document("shop-two"));
        icons.add(new Document("shopping-basket"));
        icons.add(new Document("shopping-cart"));
        icons.add(new Document("short-text"));
        icons.add(new Document("show-chart"));
        icons.add(new Document("shuffle"));
        icons.add(new Document("signal-cellular-4-bar"));
        icons.add(new Document("signal-cellular-connected-no-internet-4-bar"));
        icons.add(new Document("signal-cellular-no-sim"));
        icons.add(new Document("signal-cellular-null"));
        icons.add(new Document("signal-cellular-off"));
        icons.add(new Document("signal-wifi-4-bar"));
        icons.add(new Document("signal-wifi-4-bar-lock"));
        icons.add(new Document("signal-wifi-off"));
        icons.add(new Document("sim-card"));
        icons.add(new Document("sim-card-alert"));
        icons.add(new Document("skip-next"));
        icons.add(new Document("skip-previous"));
        icons.add(new Document("slideshow"));
        icons.add(new Document("slow-motion-video"));
        icons.add(new Document("smartphone"));
        icons.add(new Document("smoke-free"));
        icons.add(new Document("smoking-rooms"));
        icons.add(new Document("sms"));
        icons.add(new Document("sms-failed"));
        icons.add(new Document("snooze"));
        icons.add(new Document("sort"));
        icons.add(new Document("sort-by-alpha"));
        icons.add(new Document("spa"));
        icons.add(new Document("space-bar"));
        icons.add(new Document("speaker"));
        icons.add(new Document("speaker-group"));
        icons.add(new Document("speaker-notes"));
        icons.add(new Document("speaker-notes-off"));
        icons.add(new Document("speaker-phone"));
        icons.add(new Document("spellcheck"));
        icons.add(new Document("star"));
        icons.add(new Document("star-border"));
        icons.add(new Document("star-half"));
        icons.add(new Document("stars"));
        icons.add(new Document("stay-current-landscape"));
        icons.add(new Document("stay-current-portrait"));
        icons.add(new Document("stay-primary-landscape"));
        icons.add(new Document("stay-primary-portrait"));
        icons.add(new Document("stop"));
        icons.add(new Document("stop-screen-share"));
        icons.add(new Document("storage"));
        icons.add(new Document("store"));
        icons.add(new Document("store-mall-directory"));
        icons.add(new Document("straighten"));
        icons.add(new Document("streetview"));
        icons.add(new Document("strikethrough-s"));
        icons.add(new Document("style"));
        icons.add(new Document("subdirectory-arrow-left"));
        icons.add(new Document("subdirectory-arrow-right"));
        icons.add(new Document("subject"));
        icons.add(new Document("subscriptions"));
        icons.add(new Document("subtitles"));
        icons.add(new Document("subway"));
        icons.add(new Document("supervisor-account"));
        icons.add(new Document("surround-sound"));
        icons.add(new Document("swap-calls"));
        icons.add(new Document("swap-horiz"));
        icons.add(new Document("swap-vert"));
        icons.add(new Document("swap-vertical-circle"));
        icons.add(new Document("switch-camera"));
        icons.add(new Document("switch-video"));
        icons.add(new Document("sync"));
        icons.add(new Document("sync-disabled"));
        icons.add(new Document("sync-problem"));
        icons.add(new Document("system-update"));
        icons.add(new Document("system-update-alt"));
        icons.add(new Document("tab"));
        icons.add(new Document("tab-unselected"));
        icons.add(new Document("tablet"));
        icons.add(new Document("tablet-android"));
        icons.add(new Document("tablet-mac"));
        icons.add(new Document("tag-faces"));
        icons.add(new Document("tap-and-play"));
        icons.add(new Document("terrain"));
        icons.add(new Document("text-fields"));
        icons.add(new Document("text-format"));
        icons.add(new Document("textsms"));
        icons.add(new Document("texture"));
        icons.add(new Document("theaters"));
        icons.add(new Document("thumb-down"));
        icons.add(new Document("thumb-up"));
        icons.add(new Document("thumbs-up-down"));
        icons.add(new Document("time-to-leave"));
        icons.add(new Document("timelapse"));
        icons.add(new Document("timeline"));
        icons.add(new Document("timer"));
        icons.add(new Document("timer-10"));
        icons.add(new Document("timer-3"));
        icons.add(new Document("timer-off"));
        icons.add(new Document("title"));
        icons.add(new Document("toc"));
        icons.add(new Document("today"));
        icons.add(new Document("toll"));
        icons.add(new Document("tonality"));
        icons.add(new Document("touch-app"));
        icons.add(new Document("toys"));
        icons.add(new Document("track-changes"));
        icons.add(new Document("traffic"));
        icons.add(new Document("train"));
        icons.add(new Document("tram"));
        icons.add(new Document("transfer-within-a-station"));
        icons.add(new Document("transform"));
        icons.add(new Document("translate"));
        icons.add(new Document("trending-down"));
        icons.add(new Document("trending-flat"));
        icons.add(new Document("trending-up"));
        icons.add(new Document("tune"));
        icons.add(new Document("turned-in"));
        icons.add(new Document("turned-in-not"));
        icons.add(new Document("tv"));
        icons.add(new Document("unarchive"));
        icons.add(new Document("undo"));
        icons.add(new Document("unfold-less"));
        icons.add(new Document("unfold-more"));
        icons.add(new Document("update"));
        icons.add(new Document("usb"));
        icons.add(new Document("verified-user"));
        icons.add(new Document("vertical-align-bottom"));
        icons.add(new Document("vertical-align-center"));
        icons.add(new Document("vertical-align-top"));
        icons.add(new Document("vibration"));
        icons.add(new Document("video-call"));
        icons.add(new Document("video-label"));
        icons.add(new Document("video-library"));
        icons.add(new Document("videocam"));
        icons.add(new Document("videocam-off"));
        icons.add(new Document("videogame-asset"));
        icons.add(new Document("view-agenda"));
        icons.add(new Document("view-array"));
        icons.add(new Document("view-carousel"));
        icons.add(new Document("view-column"));
        icons.add(new Document("view-comfy"));
        icons.add(new Document("view-compact"));
        icons.add(new Document("view-day"));
        icons.add(new Document("view-headline"));
        icons.add(new Document("view-list"));
        icons.add(new Document("view-module"));
        icons.add(new Document("view-quilt"));
        icons.add(new Document("view-stream"));
        icons.add(new Document("view-week"));
        icons.add(new Document("vignette"));
        icons.add(new Document("visibility"));
        icons.add(new Document("visibility-off"));
        icons.add(new Document("voice-chat"));
        icons.add(new Document("voicemail"));
        icons.add(new Document("volume-down"));
        icons.add(new Document("volume-mute"));
        icons.add(new Document("volume-off"));
        icons.add(new Document("volume-up"));
        icons.add(new Document("vpn-key"));
        icons.add(new Document("vpn-lock"));
        icons.add(new Document("wallpaper"));
        icons.add(new Document("warning"));
        icons.add(new Document("watch"));
        icons.add(new Document("watch-later"));
        icons.add(new Document("wb-auto"));
        icons.add(new Document("wb-cloudy"));
        icons.add(new Document("wb-incandescent"));
        icons.add(new Document("wb-iridescent"));
        icons.add(new Document("wb-sunny"));
        icons.add(new Document("wc"));
        icons.add(new Document("web"));
        icons.add(new Document("web-asset"));
        icons.add(new Document("weekend"));
        icons.add(new Document("whatshot"));
        icons.add(new Document("widgets"));
        icons.add(new Document("wifi"));
        icons.add(new Document("wifi-lock"));
        icons.add(new Document("wifi-tethering"));
        icons.add(new Document("work"));
        icons.add(new Document("wrap-text"));
        icons.add(new Document("youtube-searched-for"));
        icons.add(new Document("zoom-in"));
        icons.add(new Document("zoom-out"));
        icons.add(new Document("zoom-out-map"));

        faIcons = new ArrayList<>();
        /* faIcons.add(new Document("pi pi-fw pi-bed", "pi-bed"));
        faIcons.add(new Document("pi pi-fw pi-buysellads", "pi-buysellads"));
        faIcons.add(new Document("pi pi-fw pi-cart-arrow-down", "pi-cart-arrow-down"));
        faIcons.add(new Document("pi pi-fw pi-cart-plus", "pi-cart-plus"));
        faIcons.add(new Document("pi pi-fw pi-connectdevelop", "pi-connectdevelop"));
        faIcons.add(new Document("pi pi-fw pi-dashcube", "pi-dashcube"));
        faIcons.add(new Document("pi pi-fw pi-diamond", "pi-diamond"));
        faIcons.add(new Document("pi pi-fw pi-facebook-official", "pi-facebook-official"));
        faIcons.add(new Document("pi pi-fw pi-forumbee", "pi-forumbee"));
        faIcons.add(new Document("pi pi-fw pi-heartbeat", "pi-heartbeat"));
        faIcons.add(new Document("pi pi-fw pi-hotel", "pi-hotel (alias)"));
        faIcons.add(new Document("pi pi-fw pi-leanpub", "pi-leanpub"));
        faIcons.add(new Document("pi pi-fw pi-mars", "pi-mars"));
        faIcons.add(new Document("pi pi-fw pi-mars-double", "pi-mars-double"));
        faIcons.add(new Document("pi pi-fw pi-mars-stroke", "pi-mars-stroke"));
        faIcons.add(new Document("pi pi-fw pi-mars-stroke-h", "pi-mars-stroke-h"));
        faIcons.add(new Document("pi pi-fw pi-mars-stroke-v", "pi-mars-stroke-v"));
        faIcons.add(new Document("pi pi-fw pi-medium", "pi-medium"));
        faIcons.add(new Document("pi pi-fw pi-mercury", "pi-mercury"));
        faIcons.add(new Document("pi pi-fw pi-motorcycle", "pi-motorcycle"));
        faIcons.add(new Document("pi pi-fw pi-neuter", "pi-neuter"));
        faIcons.add(new Document("pi pi-fw pi-pinterest-p", "pi-pinterest-p"));
        faIcons.add(new Document("pi pi-fw pi-sellsy", "pi-sellsy"));*/
        faIcons.add(new Document("pi pi-fw pi-server", "pi-server"));
        /*faIcons.add(new Document("pi pi-fw pi-ship", "pi-ship"));
        faIcons.add(new Document("pi pi-fw pi-shirtsinbulk", "pi-shirtsinbulk"));
        faIcons.add(new Document("pi pi-fw pi-simplybuilt", "pi-simplybuilt"));
        faIcons.add(new Document("pi pi-fw pi-skyatlas", "pi-skyatlas"));
        faIcons.add(new Document("pi pi-fw pi-street-view", "pi-street-view"));
        faIcons.add(new Document("pi pi-fw pi-subway", "pi-subway"));
        faIcons.add(new Document("pi pi-fw pi-train", "pi-train"));
        faIcons.add(new Document("pi pi-fw pi-transgender", "pi-transgender"));
        faIcons.add(new Document("pi pi-fw pi-transgender-alt", "pi-transgender-alt"));*/
        faIcons.add(new Document("pi pi-fw pi-user-plus", "pi-user-plus"));
        /*faIcons.add(new Document("pi pi-fw pi-user-secret", "pi-user-secret"));
        faIcons.add(new Document("pi pi-fw pi-user-times", "pi-user-times"));
        faIcons.add(new Document("pi pi-fw pi-venus", "pi-venus"));
        faIcons.add(new Document("pi pi-fw pi-venus-double", "pi-venus-double"));
        faIcons.add(new Document("pi pi-fw pi-venus-mars", "pi-venus-mars"));
        faIcons.add(new Document("pi pi-fw pi-viacoin", "pi-viacoin"));*/
        faIcons.add(new Document("pi pi-fw pi-whatsapp", "pi-whatsapp"));
        //faIcons.add(new Document("pi pi-fw pi-adjust", "pi-adjust"));
        //faIcons.add(new Document("pi pi-fw pi-adn", "pi-adn"));
        faIcons.add(new Document("pi pi-fw pi-align-center", "pi-align-center"));
        faIcons.add(new Document("pi pi-fw pi-align-justify", "pi-align-justify"));
        faIcons.add(new Document("pi pi-fw pi-align-left", "pi-align-left"));
        faIcons.add(new Document("pi pi-fw pi-align-right", "pi-align-right"));
        //   faIcons.add(new Document("pi pi-fw pi-ambulance", "pi-ambulance"));
        // faIcons.add(new Document("pi pi-fw pi-anchor", "pi-anchor"));
        faIcons.add(new Document("pi pi-fw pi-android", "pi-android"));
        //   faIcons.add(new Document("pi pi-fw pi-angellist", "pi-angellist"));
        faIcons.add(new Document("pi pi-fw pi-angle-double-down", "pi-angle-double-down"));
        faIcons.add(new Document("pi pi-fw pi-angle-double-left", "pi-angle-double-left"));
        faIcons.add(new Document("pi pi-fw pi-angle-double-right", "pi-angle-double-right"));
        faIcons.add(new Document("pi pi-fw pi-angle-double-up", "pi-angle-double-up"));
        faIcons.add(new Document("pi pi-fw pi-angle-down", "pi-angle-down"));
        faIcons.add(new Document("pi pi-fw pi-angle-left", "pi-angle-left"));
        faIcons.add(new Document("pi pi-fw pi-angle-right", "pi-angle-right"));
        faIcons.add(new Document("pi pi-fw pi-angle-up", "pi-angle-up"));
        faIcons.add(new Document("pi pi-fw pi-apple", "pi-apple"));
        //      faIcons.add(new Document("pi pi-fw pi-archive", "pi-archive"));
        //     faIcons.add(new Document("pi pi-fw pi-area-chart", "pi-area-chart"));
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-down", "pi-arrow-circle-down"));
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-left", "pi-arrow-circle-left"));
        /*   faIcons.add(new Document("pi pi-fw pi-arrow-circle-o-down", "pi-arrow-circle-o-down"));
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-o-left", "pi-arrow-circle-o-left"));
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-o-right", "pi-arrow-circle-o-right"));
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-o-up", "pi-arrow-circle-o-up"));*/
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-right", "pi-arrow-circle-right"));
        faIcons.add(new Document("pi pi-fw pi-arrow-circle-up", "pi-arrow-circle-up"));
        faIcons.add(new Document("pi pi-fw pi-arrow-down", "pi-arrow-down"));
        faIcons.add(new Document("pi pi-fw pi-arrow-left", "pi-arrow-left"));
        faIcons.add(new Document("pi pi-fw pi-arrow-right", "pi-arrow-right"));
        faIcons.add(new Document("pi pi-fw pi-arrow-up", "pi-arrow-up"));
        //faIcons.add(new Document("pi pi-fw pi-arrows", "pi-arrows"));
        //faIcons.add(new Document("pi pi-fw pi-arrows-alt", "pi-arrows-alt"));
        faIcons.add(new Document("pi pi-fw pi-arrows-h", "pi-arrows-h"));
        faIcons.add(new Document("pi pi-fw pi-arrows-v", "pi-arrows-v"));
        //faIcons.add(new Document("pi pi-fw pi-asterisk", "pi-asterisk"));
        faIcons.add(new Document("pi pi-fw pi-at", "pi-at"));
        //faIcons.add(new Document("pi pi-fw pi-automobile", "pi-automobile"));
        faIcons.add(new Document("pi pi-fw pi-backward", "pi-backward"));
        faIcons.add(new Document("pi pi-fw pi-ban", "pi-ban"));
        /*faIcons.add(new Document("pi pi-fw pi-bank", "pi-bank"));
        faIcons.add(new Document("pi pi-fw pi-bar-chart", "pi-bar-chart"));
        faIcons.add(new Document("pi pi-fw pi-bar-chart-o", "pi-bar-chart-o"));
        faIcons.add(new Document("pi pi-fw pi-barcode", "pi-barcode"));*/
        faIcons.add(new Document("pi pi-fw pi-bars", "pi-bars"));
        /*faIcons.add(new Document("pi pi-fw pi-beer", "pi-beer"));
        faIcons.add(new Document("pi pi-fw pi-behance", "pi-behance"));
        faIcons.add(new Document("pi pi-fw pi-behance-square", "pi-behance-square"));*/
        faIcons.add(new Document("pi pi-fw pi-bell", "pi-bell"));
        /*faIcons.add(new Document("pi pi-fw pi-bell-o", "pi-bell-o"));
        faIcons.add(new Document("pi pi-fw pi-bell-slash", "pi-bell-slash"));
        faIcons.add(new Document("pi pi-fw pi-bell-slash-o", "pi-bell-slash-o"));
        faIcons.add(new Document("pi pi-fw pi-bicycle", "pi-bicycle"));
        faIcons.add(new Document("pi pi-fw pi-binoculars", "pi-binoculars"));
        faIcons.add(new Document("pi pi-fw pi-birthday-cake", "pi-birthday-cake"));
        faIcons.add(new Document("pi pi-fw pi-bitbucket", "pi-bitbucket"));
        faIcons.add(new Document("pi pi-fw pi-bitbucket-square", "pi-bitbucket-square"));
        faIcons.add(new Document("pi pi-fw pi-bitcoin", "pi-bitcoin"));
        faIcons.add(new Document("pi pi-fw pi-bold", "pi-bold"));*/
        faIcons.add(new Document("pi pi-fw pi-bolt", "pi-bolt"));
        //    faIcons.add(new Document("pi pi-fw pi-bomb", "pi-bomb"));
        faIcons.add(new Document("pi pi-fw pi-book", "pi-book"));
        faIcons.add(new Document("pi pi-fw pi-bookmark", "pi-bookmark"));
        //faIcons.add(new Document("pi pi-fw pi-bookmark-o", "pi-bookmark-o"));
        faIcons.add(new Document("pi pi-fw pi-briefcase", "pi-briefcase"));
        //  faIcons.add(new Document("pi pi-fw pi-btc", "pi-btc"));
        // faIcons.add(new Document("pi pi-fw pi-bug", "pi-bug"));
        faIcons.add(new Document("pi pi-fw pi-building", "pi-building"));
        /*faIcons.add(new Document("pi pi-fw pi-building-o", "pi-building-o"));
        faIcons.add(new Document("pi pi-fw pi-bullhorn", "pi-bullhorn"));
        faIcons.add(new Document("pi pi-fw pi-bullseye", "pi-bullseye"));
        faIcons.add(new Document("pi pi-fw pi-bus", "pi-bus"));
        faIcons.add(new Document("pi pi-fw pi-cab", "pi-cab"));
        faIcons.add(new Document("pi pi-fw pi-calculator", "pi-calculator"));*/
        faIcons.add(new Document("pi pi-fw pi-calendar", "pi-calendar"));
        // faIcons.add(new Document("pi pi-fw pi-calendar-o", "pi-calendar-o"));
        faIcons.add(new Document("pi pi-fw pi-camera", "pi-camera"));
        //  faIcons.add(new Document("pi pi-fw pi-camera-retro", "pi-camera-retro"));
        faIcons.add(new Document("pi pi-fw pi-car", "pi-car"));
        faIcons.add(new Document("pi pi-fw pi-caret-down", "pi-caret-down"));
        faIcons.add(new Document("pi pi-fw pi-caret-left", "pi-caret-left"));
        faIcons.add(new Document("pi pi-fw pi-caret-right", "pi-caret-right"));
        /*  faIcons.add(new Document("pi pi-fw pi-caret-square-o-down", "pi-caret-square-o-down"));
        faIcons.add(new Document("pi pi-fw pi-caret-square-o-left", "pi-caret-square-o-left"));
        faIcons.add(new Document("pi pi-fw pi-caret-square-o-right", "pi-caret-square-o-right"));
        faIcons.add(new Document("pi pi-fw pi-caret-square-o-up", "pi-caret-square-o-up"));*/
        faIcons.add(new Document("pi pi-fw pi-caret-up", "pi-caret-up"));
        /*    faIcons.add(new Document("pi pi-fw pi-cc", "pi-cc"));
        faIcons.add(new Document("pi pi-fw pi-cc-amex", "pi-cc-amex"));
        faIcons.add(new Document("pi pi-fw pi-cc-discover", "pi-cc-discover"));
        faIcons.add(new Document("pi pi-fw pi-cc-mastercard", "pi-cc-mastercard"));
        faIcons.add(new Document("pi pi-fw pi-cc-paypal", "pi-cc-paypal"));
        faIcons.add(new Document("pi pi-fw pi-cc-stripe", "pi-cc-stripe"));
        faIcons.add(new Document("pi pi-fw pi-cc-visa", "pi-cc-visa"));
        faIcons.add(new Document("pi pi-fw pi-certificate", "pi-certificate"));
        faIcons.add(new Document("pi pi-fw pi-chain", "pi-chain"));
        faIcons.add(new Document("pi pi-fw pi-chain-broken", "pi-chain-broken"));*/
        faIcons.add(new Document("pi pi-fw pi-check", "pi-check"));
        faIcons.add(new Document("pi pi-fw pi-check-circle", "pi-check-circle"));
        // faIcons.add(new Document("pi pi-fw pi-check-circle-o", "pi-check-circle-o"));
        faIcons.add(new Document("pi pi-fw pi-check-square", "pi-check-square"));
        //   faIcons.add(new Document("pi pi-fw pi-check-square-o", "pi-check-square-o"));
        faIcons.add(new Document("pi pi-fw pi-chevron-circle-down", "pi-chevron-circle-down"));
        faIcons.add(new Document("pi pi-fw pi-chevron-circle-left", "pi-chevron-circle-left"));
        faIcons.add(new Document("pi pi-fw pi-chevron-circle-right", "pi-chevron-circle-right"));
        faIcons.add(new Document("pi pi-fw pi-chevron-circle-up", "pi-chevron-circle-up"));
        faIcons.add(new Document("pi pi-fw pi-chevron-down", "pi-chevron-down"));
        faIcons.add(new Document("pi pi-fw pi-chevron-left", "pi-chevron-left"));
        faIcons.add(new Document("pi pi-fw pi-chevron-right", "pi-chevron-right"));
        faIcons.add(new Document("pi pi-fw pi-chevron-up", "pi-chevron-up"));
        //   faIcons.add(new Document("pi pi-fw pi-child", "pi-child"));
        faIcons.add(new Document("pi pi-fw pi-circle", "pi-circle"));
        /*    faIcons.add(new Document("pi pi-fw pi-circle-o", "pi-circle-o"));
        faIcons.add(new Document("pi pi-fw pi-circle-o-notch", "pi-circle-o-notch"));
        faIcons.add(new Document("pi pi-fw pi-circle-thin", "pi-circle-thin"));
        faIcons.add(new Document("pi pi-fw pi-clipboard", "pi-clipboard"));
        faIcons.add(new Document("pi pi-fw pi-clock-o", "pi-clock-o"));
        faIcons.add(new Document("pi pi-fw pi-close", "pi-close"));*/
        faIcons.add(new Document("pi pi-fw pi-cloud", "pi-cloud"));
        faIcons.add(new Document("pi pi-fw pi-cloud-download", "pi-cloud-download"));
        faIcons.add(new Document("pi pi-fw pi-cloud-upload", "pi-cloud-upload"));
        //    faIcons.add(new Document("pi pi-fw pi-cny", "pi-cny"));
        faIcons.add(new Document("pi pi-fw pi-code", "pi-code"));
        /*  faIcons.add(new Document("pi pi-fw pi-code-fork", "pi-code-fork"));
        faIcons.add(new Document("pi pi-fw pi-codepen", "pi-codepen"));
        faIcons.add(new Document("pi pi-fw pi-coffee", "pi-coffee"));*/
        faIcons.add(new Document("pi pi-fw pi-cog", "pi-cog"));
        //  faIcons.add(new Document("pi pi-fw pi-cogs", "pi-cogs"));
        //   faIcons.add(new Document("pi pi-fw pi-columns", "pi-columns"));
        faIcons.add(new Document("pi pi-fw pi-comment", "pi-comment"));
        faIcons.add(new Document("pi pi-fw pi-comment-o", "pi-comment-o"));
        faIcons.add(new Document("pi pi-fw pi-comments", "pi-comments"));
        //   faIcons.add(new Document("pi pi-fw pi-comments-o", "pi-comments-o"));
        faIcons.add(new Document("pi pi-fw pi-compass", "pi-compass"));
        //   faIcons.add(new Document("pi pi-fw pi-compress", "pi-compress"));
        faIcons.add(new Document("pi pi-fw pi-copy", "pi-copy"));
        //      faIcons.add(new Document("pi pi-fw pi-copyright", "pi-copyright"));
        faIcons.add(new Document("pi pi-fw pi-credit-card", "pi-credit-card"));
        /*      faIcons.add(new Document("pi pi-fw pi-crop", "pi-crop"));
        faIcons.add(new Document("pi pi-fw pi-crosshairs", "pi-crosshairs"));
        faIcons.add(new Document("pi pi-fw pi-css3", "pi-css3"));
        faIcons.add(new Document("pi pi-fw pi-cube", "pi-cube"));
        faIcons.add(new Document("pi pi-fw pi-cubes", "pi-cubes"));
        faIcons.add(new Document("pi pi-fw pi-cut", "pi-cut"));
        faIcons.add(new Document("pi pi-fw pi-cutlery", "pi-cutlery"));
        faIcons.add(new Document("pi pi-fw pi-dashboard", "pi-dashboard"));*/
        faIcons.add(new Document("pi pi-fw pi-database", "pi-database"));
        //  faIcons.add(new Document("pi pi-fw pi-dedent", "pi-dedent"));
        //   faIcons.add(new Document("pi pi-fw pi-delicious", "pi-delicious"));
        faIcons.add(new Document("pi pi-fw pi-desktop", "pi-desktop"));
        //    faIcons.add(new Document("pi pi-fw pi-deviantart", "pi-deviantart"));
        //   faIcons.add(new Document("pi pi-fw pi-digg", "pi-digg"));
        faIcons.add(new Document("pi pi-fw pi-dollar", "pi-dollar"));
        //   faIcons.add(new Document("pi pi-fw pi-dot-circle-o", "pi-dot-circle-o"));
        faIcons.add(new Document("pi pi-fw pi-download", "pi-download"));
        //  faIcons.add(new Document("pi pi-fw pi-dribbble", "pi-dribbble"));
        //  faIcons.add(new Document("pi pi-fw pi-dropbox", "pi-dropbox"));
        //   faIcons.add(new Document("pi pi-fw pi-drupal", "pi-drupal"));
        //   faIcons.add(new Document("pi pi-fw pi-edit", "pi-edit"));
        faIcons.add(new Document("pi pi-fw pi-eject", "pi-eject"));
        faIcons.add(new Document("pi pi-fw pi-ellipsis-h", "pi-ellipsis-h"));
        faIcons.add(new Document("pi pi-fw pi-ellipsis-v", "pi-ellipsis-v"));
        //   faIcons.add(new Document("pi pi-fw pi-empire", "pi-empire"));
        faIcons.add(new Document("pi pi-fw pi-envelope", "pi-envelope"));
        /*   faIcons.add(new Document("pi pi-fw pi-envelope-o", "pi-envelope-o"));
        faIcons.add(new Document("pi pi-fw pi-envelope-square", "pi-envelope-square"));
        faIcons.add(new Document("pi pi-fw pi-eraser", "pi-eraser"));
        faIcons.add(new Document("pi pi-fw pi-eur", "pi-eur"));*/
        faIcons.add(new Document("pi pi-fw pi-euro", "pi-euro"));
        //   faIcons.add(new Document("pi pi-fw pi-exchange", "pi-exchange"));
        //   faIcons.add(new Document("pi pi-fw pi-exclamation", "pi-exclamation"));
        faIcons.add(new Document("pi pi-fw pi-exclamation-circle", "pi-exclamation-circle"));
        faIcons.add(new Document("pi pi-fw pi-exclamation-triangle", "pi-exclamation-triangle"));
        // faIcons.add(new Document("pi pi-fw pi-expand", "pi-expand"));
        faIcons.add(new Document("pi pi-fw pi-external-link", "pi-external-link"));
        //   faIcons.add(new Document("pi pi-fw pi-external-link-square", "pi-external-link-square"));
        faIcons.add(new Document("pi pi-fw pi-eye", "pi-eye"));
        faIcons.add(new Document("pi pi-fw pi-eye-slash", "pi-eye-slash"));
        //    faIcons.add(new Document("pi pi-fw pi-eyedropper", "pi-eyedropper"));
        faIcons.add(new Document("pi pi-fw pi-facebook", "pi-facebook"));
        faIcons.add(new Document("pi pi-fw pi-facebook-square", "pi-facebook-square"));
        faIcons.add(new Document("pi pi-fw pi-fast-backward", "pi-fast-backward"));
        faIcons.add(new Document("pi pi-fw pi-fast-forward", "pi-fast-forward"));
        /*    faIcons.add(new Document("pi pi-fw pi-fax", "pi-fax"));
        faIcons.add(new Document("pi pi-fw pi-female", "pi-female"));
        faIcons.add(new Document("pi pi-fw pi-fighter-jet", "pi-fighter-jet"));*/
        faIcons.add(new Document("pi pi-fw pi-file", "pi-file"));
        /*  faIcons.add(new Document("pi pi-fw pi-file-archive-o", "pi-file-archive-o"));
        faIcons.add(new Document("pi pi-fw pi-file-audio-o", "pi-file-audio-o"));
        faIcons.add(new Document("pi pi-fw pi-file-code-o", "pi-file-code-o"));
        faIcons.add(new Document("pi pi-fw pi-file-excel-o", "pi-file-excel-o"));
        faIcons.add(new Document("pi pi-fw pi-file-image-o", "pi-file-image-o"));
        faIcons.add(new Document("pi pi-fw pi-file-movie-o", "pi-file-movie-o"));*/
        faIcons.add(new Document("pi pi-fw pi-file-o", "pi-file-o"));
        /* faIcons.add(new Document("pi pi-fw pi-file-pdf-o", "pi-file-pdf-o"));
        faIcons.add(new Document("pi pi-fw pi-file-photo-o", "pi-file-photo-o"));
        faIcons.add(new Document("pi pi-fw pi-file-picture-o", "pi-file-picture-o"));
        faIcons.add(new Document("pi pi-fw pi-file-powerpoint-o", "pi-file-powerpoint-o"));
        faIcons.add(new Document("pi pi-fw pi-file-sound-o", "pi-file-sound-o"));
        faIcons.add(new Document("pi pi-fw pi-file-text", "pi-file-text"));
        faIcons.add(new Document("pi pi-fw pi-file-text-o", "pi-file-text-o"));
        faIcons.add(new Document("pi pi-fw pi-file-video-o", "pi-file-video-o"));
        faIcons.add(new Document("pi pi-fw pi-file-word-o", "pi-file-word-o"));
        faIcons.add(new Document("pi pi-fw pi-file-zip-o", "pi-file-zip-o"));
        faIcons.add(new Document("pi pi-fw pi-files-o", "pi-files-o"));
        faIcons.add(new Document("pi pi-fw pi-film", "pi-film"));*/
        faIcons.add(new Document("pi pi-fw pi-filter", "pi-filter"));
        //  faIcons.add(new Document("pi pi-fw pi-fire", "pi-fire"));
        //  faIcons.add(new Document("pi pi-fw pi-fire-extinguisher", "pi-fire-extinguisher"));
        faIcons.add(new Document("pi pi-fw pi-flag", "pi-flag"));
        /*   faIcons.add(new Document("pi pi-fw pi-flag-checkered", "pi-flag-checkered"));
        faIcons.add(new Document("pi pi-fw pi-flag-o", "pi-flag-o"));
        faIcons.add(new Document("pi pi-fw pi-flash", "pi-flash"));
        faIcons.add(new Document("pi pi-fw pi-flask", "pi-flask"));
        faIcons.add(new Document("pi pi-fw pi-flickr", "pi-flickr"));
        faIcons.add(new Document("pi pi-fw pi-floppy-o", "pi-floppy-o"));*/
        faIcons.add(new Document("pi pi-fw pi-folder", "pi-folder"));
        //  faIcons.add(new Document("pi pi-fw pi-folder-o", "pi-folder-o"));
        faIcons.add(new Document("pi pi-fw pi-folder-open", "pi-folder-open"));
        //faIcons.add(new Document("pi pi-fw pi-folder-open-o", "pi-folder-open-o"));
        // faIcons.add(new Document("pi pi-fw pi-font", "pi-font"));
        faIcons.add(new Document("pi pi-fw pi-forward", "pi-forward"));
        /* faIcons.add(new Document("pi pi-fw pi-foursquare", "pi-foursquare"));
        faIcons.add(new Document("pi pi-fw pi-frown-o", "pi-frown-o"));
        faIcons.add(new Document("pi pi-fw pi-futbol-o", "pi-futbol-o"));
        faIcons.add(new Document("pi pi-fw pi-gamepad", "pi-gamepad"));
        faIcons.add(new Document("pi pi-fw pi-gavel", "pi-gavel"));
        faIcons.add(new Document("pi pi-fw pi-gbp", "pi-gbp"));
        faIcons.add(new Document("pi pi-fw pi-ge", "pi-ge"));
        faIcons.add(new Document("pi pi-fw pi-gear", "pi-gear"));
        faIcons.add(new Document("pi pi-fw pi-gears", "pi-gears"));
        faIcons.add(new Document("pi pi-fw pi-gift", "pi-gift"));
        faIcons.add(new Document("pi pi-fw pi-git", "pi-git"));
        faIcons.add(new Document("pi pi-fw pi-git-square", "pi-git-square"));*/
        faIcons.add(new Document("pi pi-fw pi-github", "pi-github"));
        /*   faIcons.add(new Document("pi pi-fw pi-github-alt", "pi-github-alt"));
        faIcons.add(new Document("pi pi-fw pi-github-square", "pi-github-square"));
        faIcons.add(new Document("pi pi-fw pi-gittip", "pi-gittip"));
        faIcons.add(new Document("pi pi-fw pi-glass", "pi-glass"));*/
        faIcons.add(new Document("pi pi-fw pi-globe", "pi-globe"));
        faIcons.add(new Document("pi pi-fw pi-google", "pi-google"));
        /*  faIcons.add(new Document("pi pi-fw pi-google-plus", "pi-google-plus"));
        faIcons.add(new Document("pi pi-fw pi-google-plus-square", "pi-google-plus-square"));
        faIcons.add(new Document("pi pi-fw pi-google-wallet", "pi-google-wallet"));
        faIcons.add(new Document("pi pi-fw pi-graduation-cap", "pi-graduation-cap"));
        faIcons.add(new Document("pi pi-fw pi-group", "pi-group"));
        faIcons.add(new Document("pi pi-fw pi-h-square", "pi-h-square"));
        faIcons.add(new Document("pi pi-fw pi-hacker-news", "pi-hacker-news"));
        faIcons.add(new Document("pi pi-fw pi-hand-o-down", "pi-hand-o-down"));
        faIcons.add(new Document("pi pi-fw pi-hand-o-left", "pi-hand-o-left"));
        faIcons.add(new Document("pi pi-fw pi-hand-o-right", "pi-hand-o-right"));
        faIcons.add(new Document("pi pi-fw pi-hand-o-up", "pi-hand-o-up"));
        faIcons.add(new Document("pi pi-fw pi-hdd-o", "pi-hdd-o"));
        faIcons.add(new Document("pi pi-fw pi-header", "pi-header"));
        faIcons.add(new Document("pi pi-fw pi-headphones", "pi-headphones"));*/
        faIcons.add(new Document("pi pi-fw pi-heart", "pi-heart"));
        // faIcons.add(new Document("pi pi-fw pi-heart-o", "pi-heart-o"));
        faIcons.add(new Document("pi pi-fw pi-history", "pi-history"));
        faIcons.add(new Document("pi pi-fw pi-home", "pi-home"));
        //faIcons.add(new Document("pi pi-fw pi-hospital-o", "pi-hospital-o"));
        //  faIcons.add(new Document("pi pi-fw pi-html5", "pi-html5"));
        //  faIcons.add(new Document("pi pi-fw pi-ils", "pi-ils"));
        faIcons.add(new Document("pi pi-fw pi-image", "pi-image"));
        faIcons.add(new Document("pi pi-fw pi-inbox", "pi-inbox"));
        //   faIcons.add(new Document("pi pi-fw pi-indent", "pi-indent"));
        faIcons.add(new Document("pi pi-fw pi-info", "pi-info"));
        faIcons.add(new Document("pi pi-fw pi-info-circle", "pi-info-circle"));
        //   faIcons.add(new Document("pi pi-fw pi-inr", "pi-inr"));
        faIcons.add(new Document("pi pi-fw pi-instagram", "pi-instagram"));
        /*   faIcons.add(new Document("pi pi-fw pi-institution", "pi-institution"));
        faIcons.add(new Document("pi pi-fw pi-ioxhost", "pi-ioxhost"));
        faIcons.add(new Document("pi pi-fw pi-italic", "pi-italic"));
        faIcons.add(new Document("pi pi-fw pi-joomla", "pi-joomla"));
        faIcons.add(new Document("pi pi-fw pi-jpy", "pi-jpy"));
        faIcons.add(new Document("pi pi-fw pi-jsfiddle", "pi-jsfiddle"));*/
        faIcons.add(new Document("pi pi-fw pi-key", "pi-key"));
        /*     faIcons.add(new Document("pi pi-fw pi-keyboard-o", "pi-keyboard-o"));
        faIcons.add(new Document("pi pi-fw pi-krw", "pi-krw"));
        faIcons.add(new Document("pi pi-fw pi-language", "pi-language"));
        faIcons.add(new Document("pi pi-fw pi-laptop", "pi-laptop"));
        faIcons.add(new Document("pi pi-fw pi-lastfm", "pi-lastfm"));
        faIcons.add(new Document("pi pi-fw pi-lastfm-square", "pi-lastfm-square"));
        faIcons.add(new Document("pi pi-fw pi-leaf", "pi-leaf"));
        faIcons.add(new Document("pi pi-fw pi-legal", "pi-legal"));
        faIcons.add(new Document("pi pi-fw pi-lemon-o", "pi-lemon-o"));
        faIcons.add(new Document("pi pi-fw pi-level-down", "pi-level-down"));
        faIcons.add(new Document("pi pi-fw pi-level-up", "pi-level-up"));
        faIcons.add(new Document("pi pi-fw pi-life-bouy", "pi-life-bouy"));
        faIcons.add(new Document("pi pi-fw pi-life-buoy", "pi-life-buoy"));
        faIcons.add(new Document("pi pi-fw pi-life-ring", "pi-life-ring"));
        faIcons.add(new Document("pi pi-fw pi-life-saver", "pi-life-saver"));
        faIcons.add(new Document("pi pi-fw pi-lightbulb-o", "pi-lightbulb-o"));
        faIcons.add(new Document("pi pi-fw pi-line-chart", "pi-line-chart"));*/
        faIcons.add(new Document("pi pi-fw pi-link", "pi-link"));
        faIcons.add(new Document("pi pi-fw pi-linkedin", "pi-linkedin"));
        // faIcons.add(new Document("pi pi-fw pi-linkedin-square", "pi-linkedin-square"));
        // faIcons.add(new Document("pi pi-fw pi-linux", "pi-linux"));
        faIcons.add(new Document("pi pi-fw pi-list", "pi-list"));
        /*  faIcons.add(new Document("pi pi-fw pi-list-alt", "pi-list-alt"));
        faIcons.add(new Document("pi pi-fw pi-list-ol", "pi-list-ol"));
        faIcons.add(new Document("pi pi-fw pi-list-ul", "pi-list-ul"));
        faIcons.add(new Document("pi pi-fw pi-location-arrow", "pi-location-arrow"));*/
        faIcons.add(new Document("pi pi-fw pi-lock", "pi-lock"));
        /*  faIcons.add(new Document("pi pi-fw pi-long-arrow-down", "pi-long-arrow-down"));
        faIcons.add(new Document("pi pi-fw pi-long-arrow-left", "pi-long-arrow-left"));
        faIcons.add(new Document("pi pi-fw pi-long-arrow-right", "pi-long-arrow-right"));
        faIcons.add(new Document("pi pi-fw pi-long-arrow-up", "pi-long-arrow-up"));
        faIcons.add(new Document("pi pi-fw pi-magic", "pi-magic"));
        faIcons.add(new Document("pi pi-fw pi-magnet", "pi-magnet"));
        faIcons.add(new Document("pi pi-fw pi-mail-forward", "pi-mail-forward"));
        faIcons.add(new Document("pi pi-fw pi-mail-reply", "pi-mail-reply"));
        faIcons.add(new Document("pi pi-fw pi-mail-reply-all", "pi-mail-reply-all"));
        faIcons.add(new Document("pi pi-fw pi-male", "pi-male"));*/
        faIcons.add(new Document("pi pi-fw pi-map-marker", "pi-map-marker"));
        /* faIcons.add(new Document("pi pi-fw pi-maxcdn", "pi-maxcdn"));
        faIcons.add(new Document("pi pi-fw pi-meanpath", "pi-meanpath"));
        faIcons.add(new Document("pi pi-fw pi-medkit", "pi-medkit"));
        faIcons.add(new Document("pi pi-fw pi-meh-o", "pi-meh-o"));
        faIcons.add(new Document("pi pi-fw pi-microphone", "pi-microphone"));
        faIcons.add(new Document("pi pi-fw pi-microphone-slash", "pi-microphone-slash"));*/
        faIcons.add(new Document("pi pi-fw pi-minus", "pi-minus"));
        faIcons.add(new Document("pi pi-fw pi-minus-circle", "pi-minus-circle"));
        //   faIcons.add(new Document("pi pi-fw pi-minus-square", "pi-minus-square"));
        //    faIcons.add(new Document("pi pi-fw pi-minus-square-o", "pi-minus-square-o"));
        faIcons.add(new Document("pi pi-fw pi-mobile", "pi-mobile"));
        /* faIcons.add(new Document("pi pi-fw pi-mobile-phone", "pi-mobile-phone"));
        faIcons.add(new Document("pi pi-fw pi-money", "pi-money"));
        faIcons.add(new Document("pi pi-fw pi-moon-o", "pi-moon-o"));
        faIcons.add(new Document("pi pi-fw pi-mortar-board", "pi-mortar-board"));
        faIcons.add(new Document("pi pi-fw pi-music", "pi-music"));
        faIcons.add(new Document("pi pi-fw pi-navicon", "pi-navicon"));
        faIcons.add(new Document("pi pi-fw pi-newspaper-o", "pi-newspaper-o"));
        faIcons.add(new Document("pi pi-fw pi-openid", "pi-openid"));
        faIcons.add(new Document("pi pi-fw pi-outdent", "pi-outdent"));
        faIcons.add(new Document("pi pi-fw pi-pagelines", "pi-pagelines"));
        faIcons.add(new Document("pi pi-fw pi-paint-brush", "pi-paint-brush"));
        faIcons.add(new Document("pi pi-fw pi-paper-plane", "pi-paper-plane"));
        faIcons.add(new Document("pi pi-fw pi-paper-plane-o", "pi-paper-plane-o"));*/
        faIcons.add(new Document("pi pi-fw pi-paperclip", "pi-paperclip"));
        //    faIcons.add(new Document("pi pi-fw pi-paragraph", "pi-paragraph"));
        //   faIcons.add(new Document("pi pi-fw pi-paste", "pi-paste"));
        faIcons.add(new Document("pi pi-fw pi-pause", "pi-pause"));
        //  faIcons.add(new Document("pi pi-fw pi-paw", "pi-paw"));
        faIcons.add(new Document("pi pi-fw pi-paypal", "pi-paypal"));
        faIcons.add(new Document("pi pi-fw pi-pencil", "pi-pencil"));
        //  faIcons.add(new Document("pi pi-fw pi-pencil-square", "pi-pencil-square"));
        //  faIcons.add(new Document("pi pi-fw pi-pencil-square-o", "pi-pencil-square-o"));
        faIcons.add(new Document("pi pi-fw pi-phone", "pi-phone"));
        /*   faIcons.add(new Document("pi pi-fw pi-phone-square", "pi-phone-square"));
        faIcons.add(new Document("pi pi-fw pi-photo", "pi-photo"));
        faIcons.add(new Document("pi pi-fw pi-picture-o", "pi-picture-o"));
        faIcons.add(new Document("pi pi-fw pi-pie-chart", "pi-pie-chart"));
        faIcons.add(new Document("pi pi-fw pi-pied-piper", "pi-pied-piper"));
        faIcons.add(new Document("pi pi-fw pi-pied-piper-alt", "pi-pied-piper-alt"));
        faIcons.add(new Document("pi pi-fw pi-pinterest", "pi-pinterest"));
        faIcons.add(new Document("pi pi-fw pi-pinterest-square", "pi-pinterest-square"));
        faIcons.add(new Document("pi pi-fw pi-plane", "pi-plane"));*/
        faIcons.add(new Document("pi pi-fw pi-play", "pi-play"));
        /*   faIcons.add(new Document("pi pi-fw pi-play-circle", "pi-play-circle"));
        faIcons.add(new Document("pi pi-fw pi-play-circle-o", "pi-play-circle-o"));
        faIcons.add(new Document("pi pi-fw pi-plug", "pi-plug"));*/
        faIcons.add(new Document("pi pi-fw pi-plus", "pi-plus"));
        faIcons.add(new Document("pi pi-fw pi-plus-circle", "pi-plus-circle"));
        //   faIcons.add(new Document("pi pi-fw pi-plus-square", "pi-plus-square"));
        //   faIcons.add(new Document("pi pi-fw pi-plus-square-o", "pi-plus-square-o"));
        faIcons.add(new Document("pi pi-fw pi-power-off", "pi-power-off"));
        faIcons.add(new Document("pi pi-fw pi-print", "pi-print"));
        //   faIcons.add(new Document("pi pi-fw pi-puzzle-piece", "pi-puzzle-piece"));
        //  faIcons.add(new Document("pi pi-fw pi-qq", "pi-qq"));
        faIcons.add(new Document("pi pi-fw pi-qrcode", "pi-qrcode"));
        faIcons.add(new Document("pi pi-fw pi-question", "pi-question"));
        faIcons.add(new Document("pi pi-fw pi-question-circle", "pi-question-circle"));
        /*   faIcons.add(new Document("pi pi-fw pi-quote-left", "pi-quote-left"));
        faIcons.add(new Document("pi pi-fw pi-quote-right", "pi-quote-right"));
        faIcons.add(new Document("pi pi-fw pi-ra", "pi-ra"));
        faIcons.add(new Document("pi pi-fw pi-random", "pi-random"));
        faIcons.add(new Document("pi pi-fw pi-rebel", "pi-rebel"));
        faIcons.add(new Document("pi pi-fw pi-recycle", "pi-recycle"));*/
        faIcons.add(new Document("pi pi-fw pi-reddit", "pi-reddit"));
        //faIcons.add(new Document("pi pi-fw pi-reddit-square", "pi-reddit-square"));
        faIcons.add(new Document("pi pi-fw pi-refresh", "pi-refresh"));
        /* faIcons.add(new Document("pi pi-fw pi-remove", "pi-remove"));
        faIcons.add(new Document("pi pi-fw pi-renren", "pi-renren"));
        faIcons.add(new Document("pi pi-fw pi-reorder", "pi-reorder"));
        faIcons.add(new Document("pi pi-fw pi-repeat", "pi-repeat"));*/
        faIcons.add(new Document("pi pi-fw pi-reply", "pi-reply"));
        /*     faIcons.add(new Document("pi pi-fw pi-reply-all", "pi-reply-all"));
        faIcons.add(new Document("pi pi-fw pi-retweet", "pi-retweet"));
        faIcons.add(new Document("pi pi-fw pi-rmb", "pi-rmb"));
        faIcons.add(new Document("pi pi-fw pi-road", "pi-road"));
        faIcons.add(new Document("pi pi-fw pi-rocket", "pi-rocket"));
        faIcons.add(new Document("pi pi-fw pi-rotate-left", "pi-rotate-left"));
        faIcons.add(new Document("pi pi-fw pi-rotate-right", "pi-rotate-right"));
        faIcons.add(new Document("pi pi-fw pi-rouble", "pi-rouble"));
        faIcons.add(new Document("pi pi-fw pi-rss", "pi-rss"));
        faIcons.add(new Document("pi pi-fw pi-rss-square", "pi-rss-square"));
        faIcons.add(new Document("pi pi-fw pi-rub", "pi-rub"));
        faIcons.add(new Document("pi pi-fw pi-ruble", "pi-ruble"));
        faIcons.add(new Document("pi pi-fw pi-rupee", "pi-rupee"));*/
        faIcons.add(new Document("pi pi-fw pi-save", "pi-save"));
        //    faIcons.add(new Document("pi pi-fw pi-scissors", "pi-scissors"));
        faIcons.add(new Document("pi pi-fw pi-search", "pi-search"));
        faIcons.add(new Document("pi pi-fw pi-search-minus", "pi-search-minus"));
        faIcons.add(new Document("pi pi-fw pi-search-plus", "pi-search-plus"));
        faIcons.add(new Document("pi pi-fw pi-send", "pi-send"));
        //    faIcons.add(new Document("pi pi-fw pi-send-o", "pi-send-o"));
        //  faIcons.add(new Document("pi pi-fw pi-share", "pi-share"));
        faIcons.add(new Document("pi pi-fw pi-share-alt", "pi-share-alt"));
        /*  faIcons.add(new Document("pi pi-fw pi-share-alt-square", "pi-share-alt-square"));
        faIcons.add(new Document("pi pi-fw pi-share-square", "pi-share-square"));
        faIcons.add(new Document("pi pi-fw pi-share-square-o", "pi-share-square-o"));
        faIcons.add(new Document("pi pi-fw pi-shekel", "pi-shekel"));
        faIcons.add(new Document("pi pi-fw pi-sheqel", "pi-sheqel"));*/
        faIcons.add(new Document("pi pi-fw pi-shield", "pi-shield"));
        faIcons.add(new Document("pi pi-fw pi-shopping-cart", "pi-shopping-cart"));
        faIcons.add(new Document("pi pi-fw pi-sign-in", "pi-sign-in"));
        faIcons.add(new Document("pi pi-fw pi-sign-out", "pi-sign-out"));
        //    faIcons.add(new Document("pi pi-fw pi-signal", "pi-signal"));
        faIcons.add(new Document("pi pi-fw pi-sitemap", "pi-sitemap"));
        //   faIcons.add(new Document("pi pi-fw pi-skype", "pi-skype"));
        faIcons.add(new Document("pi pi-fw pi-slack", "pi-slack"));
        /* faIcons.add(new Document("pi pi-fw pi-sliders", "pi-sliders"));
        faIcons.add(new Document("pi pi-fw pi-slideshare", "pi-slideshare"));
        faIcons.add(new Document("pi pi-fw pi-smile-o", "pi-smile-o"));
        faIcons.add(new Document("pi pi-fw pi-soccer-ball-o", "pi-soccer-ball-o"));*/
        faIcons.add(new Document("pi pi-fw pi-sort", "pi-sort"));
        /*    faIcons.add(new Document("pi pi-fw pi-sort-alpha-asc", "pi-sort-alpha-asc"));
        faIcons.add(new Document("pi pi-fw pi-sort-alpha-desc", "pi-sort-alpha-desc"));
        faIcons.add(new Document("pi pi-fw pi-sort-amount-asc", "pi-sort-amount-asc"));
        faIcons.add(new Document("pi pi-fw pi-sort-amount-desc", "pi-sort-amount-desc"));
        faIcons.add(new Document("pi pi-fw pi-sort-asc", "pi-sort-asc"));
        faIcons.add(new Document("pi pi-fw pi-sort-desc", "pi-sort-desc"));*/
        faIcons.add(new Document("pi pi-fw pi-sort-down", "pi-sort-down"));
        //  faIcons.add(new Document("pi pi-fw pi-sort-numeric-asc", "pi-sort-numeric-asc"));
        //   faIcons.add(new Document("pi pi-fw pi-sort-numeric-desc", "pi-sort-numeric-desc"));
        faIcons.add(new Document("pi pi-fw pi-sort-up", "pi-sort-up"));
        //  faIcons.add(new Document("pi pi-fw pi-soundcloud", "pi-soundcloud"));
        //    faIcons.add(new Document("pi pi-fw pi-space-shuttle", "pi-space-shuttle"));
        faIcons.add(new Document("pi pi-fw pi-spinner", "pi-spinner"));
        /*   faIcons.add(new Document("pi pi-fw pi-spoon", "pi-spoon"));
        faIcons.add(new Document("pi pi-fw pi-spotify", "pi-spotify"));
        faIcons.add(new Document("pi pi-fw pi-square", "pi-square"));
        faIcons.add(new Document("pi pi-fw pi-square-o", "pi-square-o"));
        faIcons.add(new Document("pi pi-fw pi-stack-exchange", "pi-stack-exchange"));
        faIcons.add(new Document("pi pi-fw pi-stack-overflow", "pi-stack-overflow"));*/
        faIcons.add(new Document("pi pi-fw pi-star", "pi-star"));
        /*   faIcons.add(new Document("pi pi-fw pi-star-half", "pi-star-half"));
        faIcons.add(new Document("pi pi-fw pi-star-half-empty", "pi-star-half-empty"));
        faIcons.add(new Document("pi pi-fw pi-star-half-full", "pi-star-half-full"));
        faIcons.add(new Document("pi pi-fw pi-star-half-o", "pi-star-half-o"));*/
        faIcons.add(new Document("pi pi-fw pi-star-o", "pi-star-o"));
        // faIcons.add(new Document("pi pi-fw pi-steam", "pi-steam"));
        // faIcons.add(new Document("pi pi-fw pi-steam-square", "pi-steam-square"));
        faIcons.add(new Document("pi pi-fw pi-step-backward", "pi-step-backward"));
        faIcons.add(new Document("pi pi-fw pi-step-forward", "pi-step-forward"));
        //  faIcons.add(new Document("pi pi-fw pi-stethoscope", "pi-stethoscope"));
        faIcons.add(new Document("pi pi-fw pi-stop", "pi-stop"));
        /*   faIcons.add(new Document("pi pi-fw pi-strikethrough", "pi-strikethrough"));
        faIcons.add(new Document("pi pi-fw pi-stumbleupon", "pi-stumbleupon"));
        faIcons.add(new Document("pi pi-fw pi-stumbleupon-circle", "pi-stumbleupon-circle"));
        faIcons.add(new Document("pi pi-fw pi-subscript", "pi-subscript"));
        faIcons.add(new Document("pi pi-fw pi-suitcase", "pi-suitcase"));
        faIcons.add(new Document("pi pi-fw pi-sun-o", "pi-sun-o"));
        faIcons.add(new Document("pi pi-fw pi-superscript", "pi-superscript"));
        faIcons.add(new Document("pi pi-fw pi-support", "pi-support"));*/
        faIcons.add(new Document("pi pi-fw pi-table", "pi-table"));
        faIcons.add(new Document("pi pi-fw pi-tablet", "pi-tablet"));
        // faIcons.add(new Document("pi pi-fw pi-tachometer", "pi-tachometer"));
        faIcons.add(new Document("pi pi-fw pi-tag", "pi-tag"));
        faIcons.add(new Document("pi pi-fw pi-tags", "pi-tags"));
        /*  faIcons.add(new Document("pi pi-fw pi-tasks", "pi-tasks"));
        faIcons.add(new Document("pi pi-fw pi-taxi", "pi-taxi"));
        faIcons.add(new Document("pi pi-fw pi-tencent-weibo", "pi-tencent-weibo"));
        faIcons.add(new Document("pi pi-fw pi-terminal", "pi-terminal"));
        faIcons.add(new Document("pi pi-fw pi-text-height", "pi-text-height"));
        faIcons.add(new Document("pi pi-fw pi-text-width", "pi-text-width"));
        faIcons.add(new Document("pi pi-fw pi-th", "pi-th"));*/
        faIcons.add(new Document("pi pi-fw pi-th-large", "pi-th-large"));
        //     faIcons.add(new Document("pi pi-fw pi-th-list", "pi-th-list"));
        //    faIcons.add(new Document("pi pi-fw pi-thumb-tack", "pi-thumb-tack"));
        faIcons.add(new Document("pi pi-fw pi-thumbs-down", "pi-thumbs-down"));
        //    faIcons.add(new Document("pi pi-fw pi-thumbs-o-down", "pi-thumbs-o-down"));
        //    faIcons.add(new Document("pi pi-fw pi-thumbs-o-up", "pi-thumbs-o-up"));
        faIcons.add(new Document("pi pi-fw pi-thumbs-up", "pi-thumbs-up"));
        faIcons.add(new Document("pi pi-fw pi-ticket", "pi-ticket"));
        faIcons.add(new Document("pi pi-fw pi-times", "pi-times"));
        faIcons.add(new Document("pi pi-fw pi-times-circle", "pi-times-circle"));
        /*   faIcons.add(new Document("pi pi-fw pi-times-circle-o", "pi-times-circle-o"));
        faIcons.add(new Document("pi pi-fw pi-tint", "pi-tint"));
        faIcons.add(new Document("pi pi-fw pi-toggle-down", "pi-toggle-down"));
        faIcons.add(new Document("pi pi-fw pi-toggle-left", "pi-toggle-left"));
        faIcons.add(new Document("pi pi-fw pi-toggle-off", "pi-toggle-off"));
        faIcons.add(new Document("pi pi-fw pi-toggle-on", "pi-toggle-on"));
        faIcons.add(new Document("pi pi-fw pi-toggle-right", "pi-toggle-right"));
        faIcons.add(new Document("pi pi-fw pi-toggle-up", "pi-toggle-up"));*/
        faIcons.add(new Document("pi pi-fw pi-trash", "pi-trash"));
        /*    faIcons.add(new Document("pi pi-fw pi-trash-o", "pi-trash-o"));
        faIcons.add(new Document("pi pi-fw pi-tree", "pi-tree"));
        faIcons.add(new Document("pi pi-fw pi-trello", "pi-trello"));
        faIcons.add(new Document("pi pi-fw pi-trophy", "pi-trophy"));
        faIcons.add(new Document("pi pi-fw pi-truck", "pi-truck"));
        faIcons.add(new Document("pi pi-fw pi-try", "pi-try"));
        faIcons.add(new Document("pi pi-fw pi-tty", "pi-tty"));
        faIcons.add(new Document("pi pi-fw pi-tumblr", "pi-tumblr"));
        faIcons.add(new Document("pi pi-fw pi-tumblr-square", "pi-tumblr-square"));
        faIcons.add(new Document("pi pi-fw pi-turkish-lira", "pi-turkish-lira"));
        faIcons.add(new Document("pi pi-fw pi-twitch", "pi-twitch"));*/
        faIcons.add(new Document("pi pi-fw pi-twitter", "pi-twitter"));
        /*   faIcons.add(new Document("pi pi-fw pi-twitter-square", "pi-twitter-square"));
        faIcons.add(new Document("pi pi-fw pi-umbrella", "pi-umbrella"));
        faIcons.add(new Document("pi pi-fw pi-underline", "pi-underline"));*/
        faIcons.add(new Document("pi pi-fw pi-undo", "pi-undo"));
        //    faIcons.add(new Document("pi pi-fw pi-university", "pi-university"));
        //    faIcons.add(new Document("pi pi-fw pi-unlink", "pi-unlink"));
        faIcons.add(new Document("pi pi-fw pi-unlock", "pi-unlock"));
        //    faIcons.add(new Document("pi pi-fw pi-unlock-alt", "pi-unlock-alt"));
        //    faIcons.add(new Document("pi pi-fw pi-unsorted", "pi-unsorted"));
        faIcons.add(new Document("pi pi-fw pi-upload", "pi-upload"));
        //  faIcons.add(new Document("pi pi-fw pi-usd", "pi-usd"));
        faIcons.add(new Document("pi pi-fw pi-user", "pi-user"));
        //   faIcons.add(new Document("pi pi-fw pi-user-md", "pi-user-md"));
        faIcons.add(new Document("pi pi-fw pi-users", "pi-users"));
        /*     faIcons.add(new Document("pi pi-fw pi-video-camera", "pi-video-camera"));
        faIcons.add(new Document("pi pi-fw pi-vimeo-square", "pi-vimeo-square"));
        faIcons.add(new Document("pi pi-fw pi-vine", "pi-vine"));
        faIcons.add(new Document("pi pi-fw pi-vk", "pi-vk"));*/
        faIcons.add(new Document("pi pi-fw pi-volume-down", "pi-volume-down"));
        faIcons.add(new Document("pi pi-fw pi-volume-off", "pi-volume-off"));
        faIcons.add(new Document("pi pi-fw pi-volume-up", "pi-volume-up"));
        /*   faIcons.add(new Document("pi pi-fw pi-warning", "pi-warning"));
        faIcons.add(new Document("pi pi-fw pi-wechat", "pi-wechat"));
        faIcons.add(new Document("pi pi-fw pi-weibo", "pi-weibo"));
        faIcons.add(new Document("pi pi-fw pi-weixin", "pi-weixin"));
        faIcons.add(new Document("pi pi-fw pi-wheelchair", "pi-wheelchair"));*/
        faIcons.add(new Document("pi pi-fw pi-wifi", "pi-wifi"));
        /*    faIcons.add(new Document("pi pi-fw pi-windows", "pi-windows"));
        faIcons.add(new Document("pi pi-fw pi-won", "pi-won"));
        faIcons.add(new Document("pi pi-fw pi-wordpress", "pi-wordpress"));
        faIcons.add(new Document("pi pi-fw pi-wrench", "pi-wrench"));
        faIcons.add(new Document("pi pi-fw pi-xing", "pi-xing"));
        faIcons.add(new Document("pi pi-fw pi-xing-square", "pi-xing-square"));
        faIcons.add(new Document("pi pi-fw pi-yahoo", "pi-yahoo"));
        faIcons.add(new Document("pi pi-fw pi-yelp", "pi-yelp"));
        faIcons.add(new Document("pi pi-fw pi-yen", "pi-yen"));*/
        faIcons.add(new Document("pi pi-fw pi-youtube", "pi-youtube"));
        // faIcons.add(new Document("pi pi-fw pi-youtube-play", "pi-youtube-play"));
        // faIcons.add(new Document("pi pi-fw pi-youtube-square", "pi-youtube-square")); 

    }

    public List<Document> getIcons() {
        return icons;
    }

    public void setIcons(List<Document> icons) {
        this.icons = icons;
    }

    public List<Document> getFaIcons() {
        return faIcons;
    }

    public void setFaIcons(List<Document> faIcons) {
        this.faIcons = faIcons;
    }

}
